name: my-workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: step1
       run: date
    
     - name: step2
       run: ls

     - name: step3
       run: cat README