name: my-workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4

     - name: run-script
       run: ./install.sh
    
     - name: run-commands
       run: |
         ls -ltra
         cat README
